project:
  type: website
  output-dir: docs

website:
  open-graph: true
  site-url: "https://royfrancis.github.io/quarto-typst-folium/"
  image: "assets/images/seo.webp"
  description: "A quarto PDF template for project reports."
  favicon: "assets/favicon.png"
  navbar:
    logo: "assets/logos/nbis-scilifelab.webp"
    logo-alt: "logo"
    right:
      - text: "Home"
        href: "index.qmd"
      - text: "Usage"
        href: "reports/usage.qmd"
      - text: "Versions"
        href: "CHANGELOG.md"
  page-footer:
    border: false
    left: "{{< meta current_year >}} [NBIS](https://nbis.se)"
    right: "Published with [Quarto](https://quarto.org/) v{{< meta quarto_version >}}"

format:
  html:
    theme: "assets/css/styles.scss"
    image: "assets/images/seo
    .webp"
    title-block-banner: "assets/images/banner.png"
  folium-typst: default

nbis:
  id: "0000"
  contributors:
    - name: "Person A"
      email: "name@nbis.se"
      affiliation: "NBIS"
      roles: "NBIS Staff"
    - name: "Person B"
      email: "name@nbis.se"
      affiliation: "NBIS"
      roles: "NBIS Staff"
    - name: "Name"
      email: "name@email.com"
      affiliation: "Some university"
      roles: "User"
    - name: "Name"
      email: "name@email.com"
      affiliation: "Some university"
      roles: "Principal Investigator"

filters:
  - assets/custom.lua
