project:
  type: website
  output-dir: docs

website:
  open-graph: true
  site-url: "https://royfrancis.github.io/quarto-typst-folium/"
  image: "assets/images/seo.webp"
  description: "A quarto PDF template for project reports."
  favicon: "assets/favicon.png"
  navbar:
    logo: "assets/logos/nbis-scilifelab.webp"
    logo-alt: "logo"
    right:
      - text: "Home"
        href: "index.qmd"
      - text: "Usage"
        href: "reports/usage.qmd"
      - text: "Versions"
        href: "CHANGELOG.md"
  page-footer:
    border: false
    left: "{{< meta current_year >}} [NBIS](https://nbis.se)"
    right: "Published with [Quarto](https://quarto.org/) v{{< meta quarto_version >}}"

format:
  html:
    theme: "assets/css/styles.scss"
    image: "assets/images/seo
    .webp"
    title-block-banner: "assets/images/banner.png"
  folium-typst:
    keep-typ: false
    toc: true
    toc-depth: 3
    number-sections: true
    section-numbering: 1.1.1
    columns: 1
    mainfont: "Lato"
    papersize: "a4"
    margin-left: 2.15cm
    margin-right: 2.15cm
    margin-top: 3cm
    margin-bottom: 3cm

nbis:
  id: "0000"
  class: "NBIS REPORT"
  logo: 
     path: assets/logos/nbis-scilifelab.svg
  logo-height: 0.8cm
  font-size: 12pt
  background: 
     path: assets/images/bg.png
  contributors:
    - name: "Person A"
      email: "name@nbis.se"
      affiliation: "NBIS"
      roles: "NBIS Staff"
    - name: "Person B"
      email: "name@nbis.se"
      affiliation: "NBIS"
      roles: "NBIS Staff"
    - name: "Name"
      email: "name@email.com"
      affiliation: "Some university"
      roles: "User"
    - name: "Name"
      email: "name@email.com"
      affiliation: "Some university"
      roles: "Principal Investigator"

filters:
  - assets/custom.lua
